// <auto-generated />
using System;
using ClaroFlowEngine.Api.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace ClaroFlowEngine.Api.Data.Migrations
{
    [DbContext(typeof(CfeDbContext))]
    [Migration("20260903000752_AddEscalationSupport")]
    partial class AddEscalationSupport
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.HasPostgresExtension(modelBuilder, "pgcrypto");
            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("ClaroFlowEngine.Api.Data.Entities.Customer", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("AnonymizationSource")
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("anonymization_source");

                    b.Property<DateTime?>("AnonymizedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("anonymized_at");

                    b.Property<int?>("BillingDueDay")
                        .HasColumnType("integer")
                        .HasColumnName("billing_due_day");

                    b.Property<string>("Cpf")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("cpf");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("full_name");

                    b.Property<string>("Segment")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("segment");

                    b.HasKey("Id")
                        .HasName("pk_customers");

                    b.HasIndex("Cpf")
                        .IsUnique()
                        .HasDatabaseName("ux_customers_cpf");

                    b.ToTable("customers", null, t =>
                        {
                            t.HasCheckConstraint("ck_customers_billing_due_day", "billing_due_day IS NULL OR billing_due_day BETWEEN 1 AND 28");

                            t.HasCheckConstraint("ck_customers_cpf_format", "cpf ~ '^\\d{11}$' OR cpf ~ '^[0-9a-f]{64}$'");
                        });
                });

            modelBuilder.Entity("ClaroFlowEngine.Api.Data.Entities.CustomerPlan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<Guid>("PlanId")
                        .HasColumnType("uuid")
                        .HasColumnName("plan_id");

                    b.Property<DateTime>("StartedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("started_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_customer_plans");

                    b.HasIndex("PlanId")
                        .HasDatabaseName("ix_customer_plans_plan_id");

                    b.HasIndex("CustomerId", "Active")
                        .HasDatabaseName("ix_customer_plans_customer");

                    b.ToTable("customer_plans", (string)null);
                });

            modelBuilder.Entity("ClaroFlowEngine.Api.Data.Entities.HandoffToken", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<DateTime>("ExpiresAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("expires_at");

                    b.Property<Guid>("JourneyContextId")
                        .HasColumnType("uuid")
                        .HasColumnName("journey_context_id");

                    b.Property<string>("TargetChannel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("target_channel");

                    b.Property<string>("Token")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("token");

                    b.Property<DateTime?>("UsedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("used_at");

                    b.HasKey("Id")
                        .HasName("pk_handoff_tokens");

                    b.HasIndex("JourneyContextId")
                        .HasDatabaseName("ix_handoff_tokens_journey_context_id");

                    b.HasIndex("Token")
                        .IsUnique()
                        .HasDatabaseName("ix_handoff_tokens_token");

                    b.ToTable("handoff_tokens", (string)null);
                });

            modelBuilder.Entity("ClaroFlowEngine.Api.Data.Entities.IdentityLink", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<string>("Identifier")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("identifier");

                    b.HasKey("Id")
                        .HasName("pk_identity_links");

                    b.HasIndex("CustomerId")
                        .HasDatabaseName("ix_identity_links_customer");

                    b.HasIndex("Channel", "Identifier")
                        .IsUnique()
                        .HasDatabaseName("ux_identity_links_channel_identifier");

                    b.ToTable("identity_links", (string)null);
                });

            modelBuilder.Entity("ClaroFlowEngine.Api.Data.Entities.Invoice", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateOnly>("DueDate")
                        .HasColumnType("date")
                        .HasColumnName("due_date");

                    b.Property<DateOnly>("ReferenceMonth")
                        .HasColumnType("date")
                        .HasColumnName("reference_month");

                    b.Property<string>("Status")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasDefaultValue("issued")
                        .HasColumnName("status");

                    b.Property<int>("TotalCents")
                        .HasColumnType("integer")
                        .HasColumnName("total_cents");

                    b.HasKey("Id")
                        .HasName("pk_invoices");

                    b.HasIndex("CustomerId", "ReferenceMonth")
                        .IsDescending(false, true)
                        .HasDatabaseName("ix_invoices_customer_month");

                    b.ToTable("invoices", null, t =>
                        {
                            t.HasCheckConstraint("ck_invoices_status", "status IN ('issued', 'paid', 'overdue', 'contested')");

                            t.HasCheckConstraint("ck_invoices_total_positive", "total_cents > 0");
                        });
                });

            modelBuilder.Entity("ClaroFlowEngine.Api.Data.Entities.InvoiceItem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<int>("AmountCents")
                        .HasColumnType("integer")
                        .HasColumnName("amount_cents");

                    b.Property<string>("Category")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("category");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("description");

                    b.Property<Guid>("InvoiceId")
                        .HasColumnType("uuid")
                        .HasColumnName("invoice_id");

                    b.Property<int>("Sequence")
                        .HasColumnType("integer")
                        .HasColumnName("sequence");

                    b.HasKey("Id")
                        .HasName("pk_invoice_items");

                    b.HasIndex("InvoiceId", "Sequence")
                        .IsUnique()
                        .HasDatabaseName("ux_invoice_items_invoice_sequence");

                    b.ToTable("invoice_items", (string)null);
                });

            modelBuilder.Entity("ClaroFlowEngine.Api.Data.Entities.JourneyContext", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<DateTime?>("ClosedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("closed_at");

                    b.Property<DateTime>("CreatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("created_at")
                        .HasDefaultValueSql("NOW()");

                    b.Property<string>("CurrentStep")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("current_step");

                    b.Property<Guid>("CustomerId")
                        .HasColumnType("uuid")
                        .HasColumnName("customer_id");

                    b.Property<DateTime?>("EscalatedAt")
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("escalated_at");

                    b.Property<string>("Intent")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("intent");

                    b.Property<string>("OriginChannel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("origin_channel");

                    b.Property<string>("Payload")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("payload")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("status");

                    b.Property<DateTime>("UpdatedAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("updated_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_journey_contexts");

                    b.HasIndex("Status")
                        .HasDatabaseName("ix_journey_status_open_escalated")
                        .HasFilter("status IN ('open', 'escalated')");

                    b.HasIndex("UpdatedAt")
                        .HasDatabaseName("ix_journey_open_updated")
                        .HasFilter("status = 'open'");

                    b.HasIndex("CustomerId", "Status")
                        .HasDatabaseName("ix_journey_customer_status");

                    b.ToTable("journey_contexts", null, t =>
                        {
                            t.HasCheckConstraint("ck_journey_status", "status IN ('open', 'concluded', 'expired', 'abandoned', 'escalated')");
                        });
                });

            modelBuilder.Entity("ClaroFlowEngine.Api.Data.Entities.JourneyTransition", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<string>("Channel")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)")
                        .HasColumnName("channel");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("description");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("event_type");

                    b.Property<Guid?>("JourneyContextId")
                        .HasColumnType("uuid")
                        .HasColumnName("journey_context_id");

                    b.Property<string>("Metadata")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasColumnType("jsonb")
                        .HasColumnName("metadata")
                        .HasDefaultValueSql("'{}'::jsonb");

                    b.Property<DateTime>("OccurredAt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("timestamp with time zone")
                        .HasColumnName("occurred_at")
                        .HasDefaultValueSql("NOW()");

                    b.HasKey("Id")
                        .HasName("pk_journey_transitions");

                    b.HasIndex("JourneyContextId", "OccurredAt")
                        .HasDatabaseName("ix_transitions_journey_occurred");

                    b.ToTable("journey_transitions", (string)null);
                });

            modelBuilder.Entity("ClaroFlowEngine.Api.Data.Entities.Plan", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id")
                        .HasDefaultValueSql("gen_random_uuid()");

                    b.Property<bool>("Active")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("boolean")
                        .HasDefaultValue(true)
                        .HasColumnName("active");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("code");

                    b.Property<int>("DataGb")
                        .HasColumnType("integer")
                        .HasColumnName("data_gb");

                    b.Property<int>("MonthlyPriceCents")
                        .HasColumnType("integer")
                        .HasColumnName("monthly_price_cents");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("name");

                    b.HasKey("Id")
                        .HasName("pk_plans");

                    b.HasIndex("Code")
                        .IsUnique()
                        .HasDatabaseName("ux_plans_code");

                    b.ToTable("plans", null, t =>
                        {
                            t.HasCheckConstraint("ck_plans_price_positive", "monthly_price_cents > 0");
                        });
                });

            modelBuilder.Entity("ClaroFlowEngine.Api.Data.Entities.CustomerPlan", b =>
                {
                    b.HasOne("ClaroFlowEngine.Api.Data.Entities.Customer", "Customer")
                        .WithMany("CustomerPlans")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_customer_plans_customers_customer_id");

                    b.HasOne("ClaroFlowEngine.Api.Data.Entities.Plan", "Plan")
                        .WithMany("CustomerPlans")
                        .HasForeignKey("PlanId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_customer_plans_plans_plan_id");

                    b.Navigation("Customer");

                    b.Navigation("Plan");
                });

            modelBuilder.Entity("ClaroFlowEngine.Api.Data.Entities.HandoffToken", b =>
                {
                    b.HasOne("ClaroFlowEngine.Api.Data.Entities.JourneyContext", "JourneyContext")
                        .WithMany("HandoffTokens")
                        .HasForeignKey("JourneyContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_handoff_tokens_journey_contexts_journey_context_id");

                    b.Navigation("JourneyContext");
                });

            modelBuilder.Entity("ClaroFlowEngine.Api.Data.Entities.IdentityLink", b =>
                {
                    b.HasOne("ClaroFlowEngine.Api.Data.Entities.Customer", "Customer")
                        .WithMany("IdentityLinks")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_identity_links_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ClaroFlowEngine.Api.Data.Entities.Invoice", b =>
                {
                    b.HasOne("ClaroFlowEngine.Api.Data.Entities.Customer", "Customer")
                        .WithMany("Invoices")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoices_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ClaroFlowEngine.Api.Data.Entities.InvoiceItem", b =>
                {
                    b.HasOne("ClaroFlowEngine.Api.Data.Entities.Invoice", "Invoice")
                        .WithMany("Items")
                        .HasForeignKey("InvoiceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_invoice_items_invoices_invoice_id");

                    b.Navigation("Invoice");
                });

            modelBuilder.Entity("ClaroFlowEngine.Api.Data.Entities.JourneyContext", b =>
                {
                    b.HasOne("ClaroFlowEngine.Api.Data.Entities.Customer", "Customer")
                        .WithMany("JourneyContexts")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired()
                        .HasConstraintName("fk_journey_contexts_customers_customer_id");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("ClaroFlowEngine.Api.Data.Entities.JourneyTransition", b =>
                {
                    b.HasOne("ClaroFlowEngine.Api.Data.Entities.JourneyContext", "JourneyContext")
                        .WithMany("Transitions")
                        .HasForeignKey("JourneyContextId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .HasConstraintName("fk_journey_transitions_journey_contexts_journey_context_id");

                    b.Navigation("JourneyContext");
                });

            modelBuilder.Entity("ClaroFlowEngine.Api.Data.Entities.Customer", b =>
                {
                    b.Navigation("CustomerPlans");

                    b.Navigation("IdentityLinks");

                    b.Navigation("Invoices");

                    b.Navigation("JourneyContexts");
                });

            modelBuilder.Entity("ClaroFlowEngine.Api.Data.Entities.Invoice", b =>
                {
                    b.Navigation("Items");
                });

            modelBuilder.Entity("ClaroFlowEngine.Api.Data.Entities.JourneyContext", b =>
                {
                    b.Navigation("HandoffTokens");

                    b.Navigation("Transitions");
                });

            modelBuilder.Entity("ClaroFlowEngine.Api.Data.Entities.Plan", b =>
                {
                    b.Navigation("CustomerPlans");
                });
#pragma warning restore 612, 618
        }
    }
}
